# This is the core Makefile. It is meant to be run in parallel mode.
# It assumes that the dependencies have been computed already.

# --------------------------------------------------------------------------------

# Include dependencies.

include $(DEPS)

# --------------------------------------------------------------------------------

# The basic compilation rule.

%.vo %.glob: %.v
	$(COQC) $*

