#!/bin/sh

# A file name (the name of a Coq module) must be provided on the command line.

# We remove any leading ".v" or "." suffix, so it is OK if the filename ends
# in ".v", ".", or has no extension at all.

# Here, we rebuild just the shadow files that are needed in order to work on
# this module in Proof General.

# See also the script "./check".

BASENAME=`basename -s .v $1`
BASENAME=`basename -s . $BASENAME`
rm -f targets
echo _shadow/$BASENAME.vo > targets
make targets
rm -f targets
